const TrustMetrics = () => {
  return (
    <section className="trust-metrics-section">
      <div className="container trust-metrics-container">
        <div className="trust-metrics-left">
          <h2>Why 150,000+<br/>ecommerce brands trust<br/>iBrandMark</h2>
        </div>
        <div className="trust-metrics-right">
          <div className="metric-card metric-card-1">
            <h3>₹80</h3>
            <p><strong>ROI</strong> for every ₹10 spent on iBrandMark</p>
          </div>
          <div className="metric-card metric-card-2">
            <h3>+81.8%</h3>
            <p>higher <strong>click-through rate</strong> from<br/>automated workflows</p>
          </div>
          <div className="metric-card metric-card-3">
            <h3>75%</h3>
            <p>of revenue generated by automation</p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default TrustMetrics;
